spring.datasource.url=jdbc:mysql://mysql-385a3567-celiohenrique3434-ffdb.i.aivencloud.com:20919/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_rPRbFiWmwePhAJ_Dt0o
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true